api-version: '1.21'
name: EasyJoin
version: ${project.version}
main: me.espryth.easyjoin.EasyJoinPlugin
authors: [Espryth, Mapacheee]
package-state: internal
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false