name: EasyJoin
version: ${project.version}
main: me.espryth.easyjoin.EasyJoinPlugin
api-version: '1.21'
authors: [Espryth, Mapacheee]
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:7.0.2
